# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
    
    - name : Installing Dependencies 
      run : npm install
      
    - name : Building Project
      run : npm run build
      
    - name: Committing Changes
      run: | 
        git config --global user.email "smith.gajjar@gmail.com"
        git config --global user.name "Smith Gajjar"
        git add .
        git commit -m "New Build"
        git push --set-upstream origin master
        
    - name: Deploying to Heroku
      uses: akhileshns/heroku-deploy@v3.3.6 # This is the action
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "typescript-graphql-apiv1" #Must be unique in Heroku
          heroku_email: "smith.gajjar@gmail.com"
          appdir: "build" # <- This will point to the api folder in your project
