# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
    
    - name : Install Dependencies 
      run : npm install
      
    - name : Build Project
      run : npm run build
      
    - name: Push to new branch
      run: | 
        git config --global user.email "smith.gajjar@gmail.com"
        git config --global user.name "Smith Gajjar"
        git checkout build
        git add build
        git commit -m "New Build"
        git push origin build
