# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Typescript compiler
      uses: iCrawl/action-tsc@v1
      with:
        build: "/build"
    - name: Push to new branch
      run: | 
        git add .
        git commit -m "New Build"
        git push build
